#!/usr/bin/env python

import sys;
import binascii;

sys.path.append('../../../trunk/client/')

from GoodFETAVR import GoodFETAVR;
from intelhex import IntelHex16bit, IntelHex;

#Initialize FET and set baud rate
client=GoodFETAVR();
client.serInit()

#Connect to target
client.start();

#1,000 takes an hour
trials=1000; #10,000 is smooth
skip=1;
rate=0xffff;

start=0x860;
stop=0x890;

skip=0x10;
trials=3;


print "# GoodFET EEPROM Unlock test."
print "# Count of reads with jumping glitch."

#Erase chip for baseline.
while(client.eeprompeek(0)!=0xde):
    client.start();
    client.erase();
    client.eeprompoke(0,0xDE);
    
#client.setlockbits(0xFC);


start=0x860;
stop=0x890;
trials=10;
skip=4;
#rate=0x50;

print "# %i trials/point, %i steps/point" % (trials, skip);
print "# DAC Range %04x to %04x" % (start, stop);
print "# Generated by GoodFET, http://goodfet.sf.net/"
print "# Glitch rate of %i" % rate;
print "# %i points" % ((((stop-start)/skip)**2)*trials)

for va in range(start,stop,skip):
    print "# Column %04x" % va
    for vb in range(start,stop,skip):
        client.glitchVoltages(va, vb);
        client.glitchRate(rate);
        count=0;
        for i in range(1,trials):
            client.start();
            a=client.eeprompeek(0)
            #if(a!=0x00 and a!=0xFF):
            #    print "%04x %04x:=%02x" % (va,vb,a);
            if(a==0xDE):
                count+=1;
        if(count>0):
            print "#Glitched from %04x to %04x" % (va,vb);
            print "%f, %f, %f" % (
                va*(3.3/4096.0),vb*(3.3/4096.0),
                count);
