#!/usr/bin/env python

import sys;
import binascii;

sys.path.append('../../../trunk/client/')

from GoodFETAVR import GoodFETAVR;
from intelhex import IntelHex16bit, IntelHex;

#Initialize FET and set baud rate
client=GoodFETAVR();
client.serInit()

#Connect to target
client.start();

#1,000 takes an hour
trials=10000; #10,000 is smooth
skip=0x1;

start=0x860;
stop=0x890;

print "# GoodFET AVR Instability test."
print "# Probability that locked chip dumps 0xFF when 0xFC for lockbits."
print "# Doesn't distinguish real misread from comm. error."

#Erase chip for baseline.
client.erase();
#Disable access.
client.setlockbits(0xFC);

print "# %i trials/point, %i steps/point" % (trials, skip);
print "# DAC Range %04x to %04x" % (start, stop);
print "# Generated by GoodFET, http://goodfet.sf.net/"


for voltage in range(start,stop,skip):
    client.glitchVoltages(voltage, voltage);
    count=0;
    for i in range(1,trials):
        client.start();
        if(client.lockbits()==0xFF):
            count+=1;
        #if(client.lockbits()==0xFC):
        #    count+=1;
        #if(client.eeprompeek(0)==0xde):
        #    count+=1;
        #    print "Hoorah!"
    print "%f, %f" % (voltage*(3.3/4096.0),count*1.0/trials);
    
