graphs:
	gnuplot <graphs.gnuplot
follow:
	tail -f glitch.txt
run:
	./eeprom_locked.py | tee glitch.txt | sqlite3 glitch.sql
DOCS: stability.txt
	#Docs are ready.

clean:
	#Clean it yourself.
	#This data takes some time to generate.

