#!/usr/bin/env python

import sys;
import binascii;

sys.path.append('../../../client/')

from GoodFETAVR import GoodFETAVR;
from intelhex import IntelHex16bit, IntelHex;

#Initialize FET and set baud rate
client=GoodFETAVR();
client.serInit()

#Connect to target
client.start();

trials=100; #10,000 is smooth
skip=0x1;

start=0x860;
stop=0x890;



print "# Threshold voltage test."
print "# %i trials/point, %i steps/point" % (trials, skip);
print "# DAC Range %04x to %04x" % (start, stop);
print "# Generated by GoodFET, http://goodfet.sf.net/"
for voltage in range(start,stop,skip):
    
    
    client.glitchVoltages(voltage, voltage);
    count=0;
    for i in range(1,trials):
        client.start();
        if(client.lockbits()==0xFF):
            count+=1;
    print "%f, %f" % (voltage*(3.3/4096.0),count*1.0/trials);
    
