#!/usr/bin/env python
# GoodFET Debugger
# 
# (C) 2009 Travis Goodspeed <travis at radiantmachines.com>
#
# This code is being rewritten and refactored.  You've been warned!

import sys, os, readline, code, binascii;
#import rlcompleter;

from GoodFET import GoodFET, getClient;
from GoodFETConsole import GoodFETConsole;

from intelhex import IntelHex;

if(len(sys.argv)==1):
    print "Usage: %s driver\n" % sys.argv[0];
    print "driver:= monitor | cc | avr | spi | msp430";
    print;
    print "This is an unfinished client.  You probably want goodfet.$chip instead.";
    sys.exit(1);

driver=sys.argv[1];
print "Using driver %s" % driver;
#client=eval("%s()" % driver);
client=getClient(driver);
console=client.getConsole();
console.run();

sys.exit(0);
