#!/usr/bin/env python


from DataManage import DataManage

dm = DataManage(host="thayerschool.org", db="thayersc_canbus",username="thayersc_canbus",password="c3E4&$39",table="vue2");
dm.createTable("testTest");