#!/usr/bin/env python

import sys,binascii,time,random;

sys.path.append('../../../trunk/client/')

from GoodFETCC import GoodFETCC;
from intelhex import IntelHex16bit, IntelHex;

#Initialize FET and set baud rate
client=GoodFETCC();
client.serInit()

print "-- GoodFET EEPROM Unlock test."
print "-- Count of reads with voltage glitch."

client.start();
client.erase();

secret=0x69;

#Erase chip for baseline.
while(client.CCpeekcodebyte(0)!=secret):
    print "-- Setting secret";
    client.start();
    
    #Flash the secret to the first two bytes of CODE memory.
    client.CCeraseflashbuffer();
    client.CCpokedatabyte(0xF000,secret);
    client.CCpokedatabyte(0xF001,secret);
    client.CCflashpage(0);
    
    print "-- readback %02x" % client.CCpeekcodebyte(0);
    sys.stdout.flush()

#Lock chip to unlock it later.
#client.lock();

#FFF is full voltage

vstart=0;
vstop=0x1000;  #Smaller range sometimes helps.
skip=1;

#Time Range, wide search.
tstart=0;
tstop=client.glitchstarttime();  #Really long; only use for initial investigation.

print "-- Start takes %04x cycles." % tstop;
tstep=0x1; #Must be 1


#restrict range here
vstart=0;
vstop=130;
#tstart=0;
#tstop=300;

voltages=range(vstart,vstop,skip);
times=range(tstart,tstop,tstep);

#times=[61];
trials=100;

#Self tests
print "--"
print "--"
print "-- %i trials/point, %i steps/point" % (trials, skip);
print "-- DAC Range %04x to %04x" % (vstart, vstop);
print "-- Time Range %04x to %04x" % (tstart, tstop);
print "-- Generated by GoodFET, http://goodfet.sf.net/"
print "-- %i points" % ((tstop-tstart)*(tstop-tstart)*trials/skip)
print "-- Secret %02x" % secret;

sys.stdout.flush()

random.shuffle(voltages);
random.shuffle(times);
gnd=0;     #TODO, glitch GND.
vcc=0xfff;

times=range(3,30);
voltages=range(29,0x100);
#voltages=range(0xff0,0xfff);

print ";;;;;"
print ";create table glitches(time,vcc,gnd,glitchcount,count);";
#for time in times:
for vcc in voltages:
    #for vcc in voltages:
    for time in times:
        client.glitchRate(time);
        client.glitchVoltages(gnd, vcc);  #drop voltage target
        gcount=0;
        scount=0;
        print "-- (%i,%i)" % (time,vcc);
        for i in range(0,trials):
            #client.start();
            client.glitchstart();
            
            #Try to read *0, which is secret if read works.
            a=client.CCpeekcodebyte(0x0);
            b=client.CCstatus();
            c=client.CCpeekcodebyte(0x0);
            
            if(a!=0 and a!=0xFF):
                gcount+=1;
                print "-- %04x: %02x %02x %02x" % (time, a,b,c);
            if(a==secret):
                print "-- %04x: %02x %02x %02x HELL YEAH! " % (time, a,b,c);
                sys.stdout.flush()
                scount+=1;
            
        if(gcount>0 or scount>0):
            print "insert into glitches(time,vcc,gnd,glitchcount,count)";
            print "values (%i,%i,%i,%i,%i);" % (
                time,vcc,gnd,gcount,scount);
        sys.stdout.flush()
