#!/usr/bin/env python

import sys,binascii,time,random;

sys.path.append('../../../trunk/client/')

from GoodFETCC import GoodFETCC;
from intelhex import IntelHex16bit, IntelHex;

#Initialize FET and set baud rate
client=GoodFETCC();
client.serInit()

#Connect to target
client.start();

#1,000 takes an hour
trials=10; #10,000 is smooth

print "-- GoodFET EEPROM Unlock test."
print "-- Count of reads with voltage glitch."

client.glitchVoltages(0xff0, 0xFFF);  #Jump voltage.

client.start();
client.erase();

secret=0x69;

#Erase chip for baseline.
while(client.CCpeekdatabyte(0xf800)!=secret):
    print "-- Setting secret";
    client.start();
    client.CCpokedatabyte(0xf800,secret);
    client.CCpokedatabyte(0xf801,secret);
    print "-- readback %02x" % client.CCpeekdatabyte(0xf800);

#Lock chip to unlock it later.
#client.setlockbits(0xFC);
client.lock();

#FFF is full voltage

vstart=0x000;
vstop=0xff;  #Smaller range sometimes helps.
skip=1;

#Time Range, wide search.
tstart=0;
tstop=client.glitchstarttime();  #Really long; only use for initial investigation.
#tstop=0x100;
print "-- Start takes %04x cycles." % tstop;
tstep=0x1; #Must be 1


voltages=range(vstart,vstop,skip);
times=range(tstart,tstop,tstep);

#times=[61];
trials=1;

#Self tests
print "--"
print "--"
print "-- %i trials/point, %i steps/point" % (trials, skip);
print "-- DAC Range %04x to %04x" % (vstart, vstop);
print "-- Time Range %04x to %04x" % (tstart, tstop);
print "-- Generated by GoodFET, http://goodfet.sf.net/"
print "-- %i points" % ((tstop-tstart)*(tstop-tstart)*trials/skip)
print "-- Secret %02x" % secret;

sys.stdout.flush()


random.shuffle(voltages);
#random.shuffle(times);
gnd=0; #TODO, glitch GND.

print "create table glitches(time,vcc,gnd,glitchcount,count);";
for vcc in voltages:
    client.glitchVoltages(0, vcc);  #drop voltage target
    print "-- Row %04x" % vcc;
    for time in times:
        client.glitchRate(time);
        gcount=0;
        scount=0;
        for i in range(0,trials):
            #Old start
            #client.start();
            #Glitching AVR/Start
            client.glitchstart();
            
            #Try to read *0, which is secret if read works.
            a=client.CCpeekdatabyte(0xf800);
            b=client.CCstatus();
            c=client.CCpeekdatabyte(0xf800);
            
            if(a>0):
                gcount+=1;
            print "-- %04x: %02x %02x %02x" % (time, a,b,c);
            if(a==secret):
                print "-- %04x: %02x %02x %02x HELL YEAH! " % (time, a,b,c);
                sys.stdout.flush()
                scount+=1;
            
        if(gcount>0 or scount>0):
            print "insert into glitches(time,vcc,gnd,glitchcount,count)";
            print "values (%i,%i,%i,%i,%i);" % (
                time,vcc,gnd,gcount,scount);
        sys.stdout.flush()
